SignalingConnect の `metadata`, `signaling_notify_metadata` が nil なのに送信データに {} が含まれる問題を修正
shiguredo/sora-ios-sdk pull request #198
Opened 2024-07-16 09:41 UTC by zztkm

修正内容はこちらです。

- [FIX] SignalingConnect の `metadata`, `signaling_notify_metadata` が nil の場合に {} として送信されてしまう問題を修正する

2024-07-16 10:02 UTC, torikizi approved these changes
修正ありがとうございます。
LGTM です

2024-07-16 10:45 UTC, miosakuma approved these changes
対応ありがとうございました。

2024-07-16 11:42 UTC, voluntas requested changes

2024-07-16 11:42 UTC, voluntas commented on Sora/Signaling.swift
> +            try metadata.encode(to: metadataEnc)
ここでそもそもあったらエンコードになっているのに、 container.superEncoder の影響なのでは？と思うので、そのあたりのコメントを丁寧に書いておいてください。 superEncoder を呼び出すと metadata: {} が含まれる理由まで書いてあると後でコードを見た時に困らなさそうなので。

2024-07-16 12:48 UTC, zztkm commented on Sora/Signaling.swift
> +            try metadata.encode(to: metadataEnc)
@voluntas https://github.com/shiguredo/sora-ios-sdk/pull/198/commits/ac3b80e17ffd96768c3bff4c0c32b051f2a4c466 で修正しました。

2024-07-17 00:59 UTC, voluntas approved these changes

2024-07-17 01:05 UTC, merged