Feature/webrtc logging timestamp
shiguredo/sora-ios-sdk pull request #54
Opened 2021-04-28 08:21 UTC by szktty

タイムスタンプつきの libwebrtc ログを出力する API を追加しました。

2021-04-28 08:40 UTC, enm10k requested changes
@szktty 
ありがとうございます!

コードは LGTM です
CHANGES.md の追記もお願いしたいです

2021-04-30 07:10 UTC, szktty commented
@enm10k CHANGES を更新しました。それとメソッド名がわかりにくいので setWebRTCLoggingSeverity -> setWebRTCLogLevel に変更しました。

2021-04-30 07:28 UTC, szktty commented
@enm10k 競合を修正し、変更の詳細を追記しました。

2021-04-30 23:55 UTC, enm10k commented
ありがとうございます
マージします

2021-04-30 23:55 UTC, enm10k approved these changes

2021-04-30 23:55 UTC, merged